"""End-to-end CRUD test against an in-memory SQLite database.

No PostgreSQL needed, so it runs anywhere in a second. The real deployment
uses PostgreSQL; the SQL generated by SQLAlchemy is the same for this schema.
"""

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.db import Base, get_db
from app.main import app


@pytest.fixture()
def client():
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)
    TestingSession = sessionmaker(bind=engine, autoflush=False, autocommit=False)

    def override_get_db():
        db = TestingSession()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    # No `with` block on purpose: entering the context runs the lifespan,
    # which would try to connect to the real DATABASE_URL.
    yield TestClient(app, raise_server_exceptions=True)
    app.dependency_overrides.clear()


def test_health(client):
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json() == {"status": "ok"}


def test_full_crud_flow(client):
    # create
    r = client.post(
        "/products",
        json={"name": "Test Mug", "price_cents": 1299, "image_url": "https://x.test/mug.jpg"},
    )
    assert r.status_code == 201, r.text
    product = r.json()
    pid = product["id"]
    assert product["status"] == "ACTIVE"
    assert product["currency"] == "USD"

    # list shows it
    r = client.get("/products")
    assert r.status_code == 200
    assert r.json()["total"] == 1
    assert r.json()["items"][0]["id"] == pid

    # read one
    assert client.get(f"/products/{pid}").status_code == 200

    # update price only
    r = client.put(f"/products/{pid}", json={"price_cents": 999})
    assert r.status_code == 200
    assert r.json()["price_cents"] == 999
    assert r.json()["name"] == "Test Mug"

    # take off the shelf
    r = client.delete(f"/products/{pid}")
    assert r.status_code == 204
    assert client.get("/products").json()["total"] == 0
    assert client.get("/products?include_inactive=true").json()["total"] == 1
    assert client.get(f"/products/{pid}").json()["status"] == "INACTIVE"

    # re-list via PUT
    r = client.put(f"/products/{pid}", json={"status": "ACTIVE"})
    assert r.status_code == 200
    assert client.get("/products").json()["total"] == 1


def test_validation_and_404(client):
    assert client.post("/products", json={"name": "", "price_cents": 1}).status_code == 422
    assert client.post("/products", json={"name": "x", "price_cents": -1}).status_code == 422
    assert client.post("/products", json={"name": "x", "price_cents": 1, "currency": "usd"}).status_code == 422

    missing = "00000000-0000-0000-0000-000000000000"
    assert client.get(f"/products/{missing}").status_code == 404
    assert client.put(f"/products/{missing}", json={"name": "y"}).status_code == 404
    assert client.delete(f"/products/{missing}").status_code == 404
    assert client.get("/products/not-a-uuid").status_code == 422
